# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'CandleSticks-Chart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CandleSticks-Chart
 pod  'Charts'
 pod  'TinyConstraints'
 pod 'Firebase'
 pod 'Firebase/Crashlytics'
 pod 'Firebase/Analytics'

end
